# Generated by Django 3.2.15 on 2022-09-06 02:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("media", "0010_auto_20190523_1638"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Video",
        ),
    ]
