# Generated by Django 3.2.16 on 2023-01-08 19:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("media", "0011_delete_video"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="file",
            options={
                "ordering": ["-date_added", "-pk"],
                "permissions": [
                    ("upload_dangerous_files", "Can upload dangerous files")
                ],
            },
        ),
    ]
