# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-03-10 00:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_auto_20191108_1506'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='page',
            unique_together=set([('parent', 'slug')]),
        ),
        migrations.RemoveField(
            model_name='country',
            name='group',
        ),
        migrations.RemoveField(
            model_name='page',
            name='country_group',
        ),
        migrations.RemoveField(
            model_name='page',
            name='is_content_object',
        ),
        migrations.RemoveField(
            model_name='page',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='CountryGroup',
        ),
    ]
