# Generated by Django 4.2.7 on 2023-12-29 04:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0011_remove_localisation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="page",
            name="twitter_card",
        ),
        migrations.RemoveField(
            model_name="page",
            name="twitter_description",
        ),
        migrations.RemoveField(
            model_name="page",
            name="twitter_image",
        ),
        migrations.RemoveField(
            model_name="page",
            name="twitter_title",
        ),
    ]
