# Generated by Django 5.2.8 on 2025-12-18 20:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0012_remove_page_twitter_card_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PageTreeLock",
            fields=[
                (
                    "id",
                    models.IntegerField(default=1, primary_key=True, serialize=False),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("id", 1)),
                        name="pages_pagetreelock_singleton",
                    )
                ],
            },
        ),
    ]
