# Generated by Django 3.2.15 on 2022-09-11 01:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("links", "0002_auto_20171020_1320"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="link",
            name="new_window",
        ),
    ]
